//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiveSenseV2 {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        private Gadgeteer.Modules.GHIElectronics.LightSensor lightSensor;
        
        private Gadgeteer.Modules.GHIElectronics.SDCard sdCard;
        
        private Gadgeteer.Modules.GHIElectronics.UsbClientDP usbClientDP;
        
        private Gadgeteer.Modules.GHIElectronics.WiFi_RS21 wifi_RS21;
        
        private Gadgeteer.Modules.Seeed.Accelerometer accelerometer;
        
        private Gadgeteer.Modules.Seeed.TemperatureHumidity temperatureHumidity;
        
        private Gadgeteer.Modules.Seeed.Barometer barometer;
        
        private Gadgeteer.Modules.GHIElectronics.Camera camera;
        
        private Gadgeteer.Modules.GHIElectronics.Button button;
        
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZSpider();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.usbClientDP = new GTM.GHIElectronics.UsbClientDP(1);
            this.camera = new GTM.GHIElectronics.Camera(3);
            this.barometer = new GTM.Seeed.Barometer(4);
            this.sdCard = new GTM.GHIElectronics.SDCard(5);
            this.wifi_RS21 = new GTM.GHIElectronics.WiFi_RS21(6);
            this.button = new GTM.GHIElectronics.Button(8);
            this.lightSensor = new GTM.GHIElectronics.LightSensor(9);
            this.accelerometer = new GTM.Seeed.Accelerometer(10);
            this.temperatureHumidity = new GTM.Seeed.TemperatureHumidity(12);
        }
    }
}
